### ISSUE TITLE
Global middleware outputs not available in `authMiddlewareMap`

### ISSUE THREAD

**Issue by codetheweb** [seamapi/edgespec#52]
throws a type error:

<img width="731" alt="Screenshot 2024-02-02 at 19 54 12" src="https://github.com/seamapi/edgespec/assets/7410405/060233eb-5a9b-4606-9ce9-cd39ce391323">

```ts
export const withDb: Middleware<{ db?: Database }, {db: Database}>

export const withLanAuth: Middleware<
{ db: Database },
  { device: StoredDevice }
> 
```

**Comment by mxsdev** [comment]
ah, yeah i know why this is, one sec
