### ISSUE TITLE
Add `edgespec codegen` command

### ISSUE THREAD

**Issue by codetheweb** [seamapi/edgespec#8]
Should generate:

- [ ] OpenAPI spec
- [x] TypeScript route spec
- [ ] Zod types?

**Comment by mxsdev** [comment]
@codetheweb is this finished?

**Comment by codetheweb** [comment]
no, but we can make a separate issue for openapi generation and close this if you want

**Comment by codetheweb** [comment]
https://github.com/seamapi/edgespec/issues/101
